In [18]:
#1.) Load image in the script
# 2.) Randomly crop the image ensuring the samples don't overlap
# 3.) Crop the image and show the user the samples
# 4.) Allow the user to resize the cropped images and show the new images
# 5.) Add error handling

# Things to check once the script is ready:
# a) Make sure there's error handling, especially for when the user tries to configure the sample size
# b) Make sure there's room for other developers to add other transformations before or after the sampling

In [4]:
#1.) Load image in the script
from PIL import Image

print('This programme will allow you to cut three random samples from an image.\nThe image in question will appear in another application shortly.')
with Image.open('surgical_robot.jpeg') as im:
    im.show()
    print(f'The image\'s details are as follows.\nImage format: {im.format}.\nImage size: {im.size}.')

# region.show()

# # im.show()

# im.close()


This programme will allow you to cut three random samples from an image.
The image in question will appear in another application shortly.
The image's details are as follows.
Image format: JPEG.
Image size: (1271, 847).


In [67]:
import random
import numpy as np

def min_coord(a):
    if a == 0:
        numb = 1
    else:
        numb = a + 1
    return numb

def x_max_coord(a):
    if a == 1272:
        numb = 1271
    else:
        numb = 1272
    return numb

def y_max_coord(a):
    if a == 848:
        numb = 847
    else:
        numb = 848
    return numb
    #     num_list = range(1272)
    #     num_list2 = [x != a for x in num_list]
    #     numb = random.choice(num_list2)
    # return numb

# Calculating the area of the shape
def calc_area(polygon):
    if polygon[0] > polygon [2]:
        width = polygon[0] - polygon[2]
    else:
        width = polygon[2] - polygon[0]
    
    if polygon[1] > polygon[3]:
        length = polygon[1] - polygon[3]
    else:
        length = polygon[3] - polygon[1]
    
    area = width * length
    return area

space = 361000
i = 0
while space > 360000:
    print(i)
    shape = np.random.randint([0,0], [1272,848])
    shape2 = np.random.randint([min_coord(shape[0]), min_coord(shape[1])], [x_max_coord(shape[0]), y_max_coord(shape[1])])
    shape3 = np.append(shape, shape2)
    space = int(calc_area(shape3))
    i += 1
    print(i)
    print(shape3)
    print(space)

# Add logic to check that the cropped space's area is not greater than 360,000. In the interst of time, change the logic so that the first
# coord is always smaller than the second axis pair.

0
1
[1045  652 1229  684]
5888


In [46]:
# Create code that then generates coords for the two other shapes and looks in the numpy matrix column to make sure it's not going in the
# same place as previous entries.

def other_x_min_coord(polygons):
    x_coords = []

    for polygon in polygons:
        x_coords.append(polygon[0])
        x_coords.append(polygon[2])

    x_coords.sort()
    return x_coords[0]

def second_other_x_min_coord(polygons, x_coord):
    x_coords = []
    
    x_coords.append(x_coord)

    for polygon in polygons:
        x_coords.append(polygon[0])
        x_coords.append(polygon[2])

    x_coords.sort()
    return x_coords[0]

def other_y_min_coord(polygons):
    y_coords = []

    for polygon in polygons:
        y_coords.append(polygon[1])
        y_coords.append(polygon[3])

    y_coords.sort()
    return y_coords[0]

def second_other_y_min_coord(polygons, y_coord):
    y_coords = []

    y_coords.append(y_coord)

    for polygon in polygons:
        y_coords.append(polygon[1])
        y_coords.append(polygon[3])

    y_coords.sort()
    return y_coords[0]

def other_x_max_coord(polygons):
    x_coords = []

    for polygon in polygons:
        x_coords.append(polygon[0])
        x_coords.append(polygon[2])
    
    x_coords.sort()
    if x_coords[0] != 1272:
        x_max = 1272
    else:
        x_max = x_coords[0]

    return x_max

def second_other_x_max_coord(polygons, x_coord):
    x_coords = []

    x_coords.append(x_coord)

    for polygon in polygons:
        x_coords.append(polygon[0])
        x_coords.append(polygon[2])
    
        x_coords.sort()
        if x_coords[-1] != 1272:
            x_max = 1272
        else:
            x_max = x_coords[-1]
    return x_max

def other_y_max_coord(polygons):
    y_coords = []

    for polygon in polygons:
        y_coords.append(polygon[1])
        y_coords.append(polygon[3])
    
    y_coords.sort()

    if y_coords[-1] != 848:
        y_max = 848
    else:
        y_max = y_coords[-1]

    return y_max

def second_other_y_max_coord(polygons, y_coord):
    y_coords = []

    y_coords.append(y_coord)

    for polygon in polygons:
        y_coords.append(polygon[1])
        y_coords.append(polygon[3])
    
    y_coords.sort()

    if y_coords[-1] != 848:
        y_max = 848
    else:
        y_max = y_coords[-1]

    return y_max

shapes = np.array([shape3])

print(shapes)

space2 = 361000
i = 0
while space2 > 360000:
    print(i)
    shape4 = np.random.randint([other_x_min_coord(shapes), other_y_min_coord(shapes)], [other_x_max_coord(shapes),other_y_max_coord(shapes)])
    shape5 = np.random.randint([second_other_x_min_coord(shapes, shape4[0]), second_other_y_min_coord(shapes, shape4[1])], [second_other_x_max_coord(shapes, shape4[0]), second_other_y_max_coord(shapes, shape4[1])])
    shape6 = np.append(shape4, shape5)

    space2 = int(calc_area(shape6))
    i += 1
    print(i)
    print(shape6)
    print(space2)




[[797 121 988 306]]
1
2
[ 935  599 1225  676]
22330


In [48]:
print(shapes)
shapes = np.concatenate((shapes, [shape6]))
print(shapes)
print(shape6)

[[797 121 988 306]]
[[ 797  121  988  306]
 [ 935  599 1225  676]]
[ 935  599 1225  676]


In [54]:
# Create a function that creates the first shape and then a function that creates the next two shapes.

def first_shape():
    space = 361000
    while space > 360000:
        shape = np.random.randint([0,0], [1272,848])
        shape2 = np.random.randint([min_coord(shape[0]), min_coord(shape[1])], [x_max_coord(shape[0]), y_max_coord(shape[1])])
        shape3 = np.append(shape, shape2)
        space = int(calc_area(shape3))
    
    shape3 = np.array([shape3])
    return shape3

def other_shapes():
    shapes = first_shape()

    space2 = 361000
    while space2 > 360000:
        shape4 = np.random.randint([other_x_min_coord(shapes), other_y_min_coord(shapes)], [other_x_max_coord(shapes),other_y_max_coord(shapes)])
        shape5 = np.random.randint([second_other_x_min_coord(shapes, shape4[0]), second_other_y_min_coord(shapes, shape4[1])], [second_other_x_max_coord(shapes, shape4[0]), second_other_y_max_coord(shapes, shape4[1])])
        shape6 = np.append(shape4, shape5)
        space2 = int(calc_area(shape6))
    
    shape6 = np.array([shape6])
    return shape6


shapes = np.concatenate((first_shape(), other_shapes()))
print(shapes)
shapes = np.concatenate((shapes, other_shapes()))
print(shapes)



[[1047  303  133  117]
 [ 408  780  737  773]]
[[1047  303  133  117]
 [ 408  780  737  773]
 [ 633  155 1122  777]]


In [ ]:
# Then use resize and input to allow the user to resize the image according to their taste. Research max pixel width and length on this
# screen to add as a reference. Add error handling.

# I will cap sizes at 2000 x 1500

def crop_image(polygons):
    with Image.open('surgical_robot.jpeg') as im:
        for polygon in polygons:
            box = tuple(polygon)
            sample = im.crop(box)
            sample.show()

In [ ]:
def get_stuff(quantity):
    for i in range(quantity):
            x_axes = np.random.randint(1, 1270, size=(4,2))

In [68]:
def first_shape():
    space = 361000
    while space > 360000:
        shape = np.random.randint([0,0], [1271,847])
        print(shape)
        shape2 = np.random.randint([min_coord(shape[0]), min_coord(shape[1])], [1272, 848])
        shape3 = np.append(shape, shape2)
        space = int(calc_area(shape3))
    
    shape3 = np.array([shape3])
    return shape3

print(first_shape())

[926 268]
[[ 926  268 1175  827]]


In [70]:
testing_ps = [[1051,55,1240,402], [926,268,1175,827]]
missable_coords = []
for polygon in polygons:
    missable = range(polygon[0], polygon[2])
    for num in missable:
        missable_coords.append(num)
missable_coords.sort()
missable_coords = set(missable_coords)
print(missable_coords)

{926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104,

In [73]:
a = range(1272)
a[-1]
others = []
for num in a:
    if num in missable_coords:
        pass
    else:
        others.append(num)

print(others)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [74]:
def other_x_min_coord(polygons):
    missable_coords = []
    for polygon in polygons:
        missable = range(polygon[0], polygon[2])
        for num in missable:
            missable_coords.append(num)
    missable_coords.sort()
    missable_coords = set(missable_coords)
    a = range(1272)
    others = []
    for num in a:
        if num in missable_coords:
            pass
        else:
            others.append(num)
    return others

def other_y_min_coord(polygons):
    missable_coords = []
    for polygon in polygons:
        missable = range(polygon[0], polygon[2])
        for num in missable:
            missable_coords.append(num)
    missable_coords.sort()
    missable_coords = set(missable_coords)
    a = range(848)
    others = []
    for num in a:
        if num in missable_coords:
            pass
        else:
            others.append(num)
    return others

320 427


In [79]:
def other_x_max_coord(polygons, x_coord):
    x_coords = []

    for polygon in polygons:
        x_coords.append(polygon[0])
        x_coords.append(polygon[2])
    
    x_coords.append(x_coord)
    x_coords.sort()

    if x_coord == x_coords[-1]:
        x_max_coord = x_coord
    else:
        x_max_coord = x_coords[x_coords.index(x_coord) + 1]
    
    width = np.random.randint(x_coord, x_max_coord+1)

    return width

def other_y_max_coord(polygons, y_coord):
    y_coords = []

    for polygon in polygons:
        y_coords.append(polygon[0])
        y_coords.append(polygon[2])
    
    y_coords.append(y_coord)
    y_coords.sort()

    if y_coord == y_coords[-1]:
        y_max_coord = y_coord
    else:
        y_max_coord = y_coords[y_coords.index(y_coord) + 1]
    
    height = np.random.randint(y_coord, y_max_coord+1)

    return height

In [85]:
testing_ps = [[1051,55,1240,402], [926,268,1175,827]]
left = np.random.choice(other_x_min_coord())
top = np.random.choice(other_y_min_coord(testing_ps))
width = other_x_max_coord(testing_ps, testing)
height = other_y_max_coord(testing_ps, testing2)

new_shape = np.array([left,top,width,height])

print(new_shape)

[ 63 364 551 909]


In [2]:
# 2.) Ask user for the size of each sample they want
from PIL import Image
import numpy as np

print('This programme needs you to specify the size of the image samples.\nYou will need to provide a four-tuple to do this.')
print('Please keep in mind the size of the image and that the programme uses a coordinate system with (0, 0) in the upper left corner.')
print('An image demonstrating how your four-tuple will crop the image will be displayed in another application shortly.')
with Image.open('pillow_coordinate_crop.jpg') as coords_im:
    # coords_im.show()
    coords_im.size

# Get the user to enter their co-ords in the format 1,2,3,4. Then split by comma and put into a tuple.
# To ensure no overlapping, do the following: start testing with 2 samples; create a matrix and check the relationship between
# relevant columns and throw an error message when needed; add a third sample and repeat; add a fourth sample and repeat.
def get_first_sample_size(coord_sets):
    tries = 3
    sample = ''
    dig_check = ''
    for i in range(tries):
        try:
            sample = input('Kindly enter the size of your sample in the format 0,0,0,0: ')
            sample = sample.split(',')
            sample = np.array([sample])
            dig_check = ''.join(sample)
            if len(sample) != coord_sets:
                raise IndexError('Kindly enter four numbers separated by commas and four numbers separated by commas only.')
            if dig_check.isdigit() is False or not dig_check:
                raise ValueError('Kindly enter four numbers separated by commas and four numbers separated by commas only.')
            else:
                break
        except IndexError as e:
            print(e)
            if i < tries - 1:
                continue
            else:
                break
        except ValueError as e2:
            print(e2)
            if i < tries - 1:
                continue
            else:
                break
    return sample

get_first_sample_size(4)

This programme needs you to specify the size of the image samples.
You will need to provide a four-tuple to do this.
Please keep in mind the size of the image and that the programme uses a coordinate system with (0, 0) in the upper left corner.
An image demonstrating how your four-tuple will crop the image will be displayed in another application shortly.
Kindly enter four numbers separated by commas and four numbers separated by commas only.
Kindly enter four numbers separated by commas and four numbers separated by commas only.


array(['100', '100', '400', '400'], dtype='<U3')

In [ ]:
import numpy as np
# Use numpy to create a matrix above this line.
# Change the function below so that it doesn't overlap the shapes earlier on in the matrix
# (e.g. the first coordinate must be smaller than the first coordinate in the previous row and greater than the third coordinate
# in the previous row).

def get_other_sample_sizes(coord_sets, coords):
    tries = 3
    sample2 = ''
    dig_check = ''
    for i in range(tries):
        try:
            sample2 = input('Kindly enter the size of your next sample in the format 0,0,0,0: ')
            sample2 = sample2.split(',')
            sample2 = np.array([sample2])
            shape_list = np.append(coords, sample2, axis=0)
            dig_check = ''.join(sample2)
            if len(sample2) != coord_sets:
                raise IndexError('Kindly enter four numbers separated by commas and four numbers separated by commas only.')
            if dig_check.isdigit() is False or not dig_check:
                raise ValueError('Kindly enter four numbers separated by commas and four numbers separated by commas only.')
            else:
                break
        except IndexError as e:
            print(e)
            if i < tries - 1:
                continue
            else:
                break
        except ValueError as e2:
            print(e2)
            if i < tries - 1:
                continue
            else:
                break
    return sample2

get_other_sample_sizes(4, get_first_sample_size(4))
# print(sample1, sample2, s1_dig_check, s2_dig_check)
# region = im.crop(box)

In [9]:
import sys

def resize_request():
    decision = input('Do you want to resize the cropped image? (Y/N): ')
    if decision == 'Y':
        goal = 2
        retries = 3

        for i in range(retries):
            try:
                new_size = input('Maximum size is 2000 x 1500. Kindly enter the size you want the cropped image in the format 0,0: ')
                sizes = []
                new_size = new_size.split(',')
                dig_check = ''.join(new_size)
                for num in new_size:
                    sizes.append(int(num))
                sizes = tuple(sizes)
                if len(new_size) != goal:
                    raise IndexError('Kindly enter two numbers (first up to 2000 and second up to 1500) separated by commas and two numbers separated by commas only.')
                if dig_check.isdigit() is False or not dig_check:
                    raise ValueError('Kindly enter four numbers separated by commas and four numbers separated by commas only.')
                else:
                    break
            except IndexError as e:
                print(e)
                if i < retries - 1:
                    continue
                else:
                    print('Restart this programme and follow the instructions more carefully when you re-run it.')
                    sys.exit()
            except ValueError as e2:
                print(e2)
                if i < retries - 1:
                    continue
                else:
                    print('Restart this programme and follow the instructions more carefully when you re-run it.')
                    sys.exit()
        
        return sizes
    else:
        print('Cropped image will not be resized')

gf = resize_request()
print(type(gf))

<class 'tuple'>
